include( ../coreplugin/coreplugin.pri )
include( ../listviewplugin/listviewplugin.pri )
include( ../icdplugin/icdplugin.pri )
include( ../categoryplugin/categoryplugin.pri )
include( ../texteditorplugin/texteditorplugin.pri )
