.TH FreeDiams 1 "17 February 2012"
.SH NAME
FreeDiams \- pharmaceutical drugs prescriptor
.SH SYNOPSIS
.B freediams
.SH DESCRIPTION
.B FreeDiams
prescriber is the result of FreeMedForms prescriber
plugins built into a standalone application.
It is developed by medical doctors and is intended
for use by these same professionals. It can be used alone to
prescribe and / or test drug interactions within a prescription.
It can be linked to any application thanks to its command line
parameters.
.P
.B FreeDiams                                                                                                                                                                     
can use multiple drugs database. By default, only the
FDA (USA) database is installed. You can download and
install new database directly from the application.
.P
.B FreeDiams
is fully integrated in the
.B FreeMedForms
open source EMR and can be used as external
prescriber by any EMR using its interoperability
interface.

.SH "OPTIONS"
.LP
.TP
\fB\-v / \-\-version\fR
Displays the current version of FreeDiams.
.TP
\fB\-\-exchange-in=</path/to/xml/exchange-in.xml>\fR
defines the "in" exchange file.
.P
More parameters are documented at
.P
http://www.freemedforms.com/en/manuals/freediams/command_line

.SH AUTHOR
Eric Maeker, MD <eric.maeker at gmail dot com>
.SH "SEE ALSO"
.br
.B http://www.freemedforms.com/
