--
-- Database: `fmf_xmlforms`
--
-- Update version 0.1 to version 1
--

CREATE TABLE SCHEMA_CHANGES(
   ID integer PRIMARY KEY NOT NULL,
   VERSION_NUMBER integer NOT NULL,
   SCRIPT_NAME varchar(255) NOT NULL,
   TIMESTAMP_UTC_APPLIED varchar(19) NOT NULL);

DROP TABLE IF EXISTS `VERSION`;

INSERT INTO SCHEMA_CHANGES(VERSION_NUMBER, SCRIPT_NAME, TIMESTAMP_UTC_APPLIED) VALUES(1, 'updatesqlitexmlforms1.sql', datetime());
