--
-- Database: `fmf_xmlforms`
--
-- Update version 0.1 to version 1
--

DROP INDEX `FORMS__FORM_UUID ` ON FORMS;
CREATE INDEX `FORMS__FORM_UUID` ON FORMS (FORM_UUID(190));

DROP INDEX `FORMS__FORM_ORG_UUID ` ON FORMS;
CREATE INDEX `FORMS__FORM_ORG_UUID` ON FORMS (FORM_ORG_UUID(190));

CREATE TABLE `SCHEMA_CHANGES`(
   `ID` int NOT NULL AUTO_INCREMENT,
   `VERSION_NUMBER` int NOT NULL,
   `SCRIPT_NAME` varchar(255) NOT NULL,
   `TIMESTAMP_UTC_APPLIED` varchar(19) NOT NULL,
   PRIMARY KEY (ID)
);

INSERT INTO `SCHEMA_CHANGES` (`VERSION_NUMBER`, `SCRIPT_NAME`, `TIMESTAMP_UTC_APPLIED`)
VALUES ('1', 'updatexmlforms1.sql', UTC_TIMESTAMP());

DROP TABLE IF EXISTS `VERSION`;
