isudo: required
dist: trusty

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt562-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt56[QTPACKAGE] qt56svg

script:
  - source /opt/qt56/bin/qt56-env.sh
  - /opt/qt56/bin/qmake freehealth/freehealth.pro -r "CONFIG+=debug debug_without_install"
  - make
