--
-- Database: `fmf_users`
--
-- Update all previous versions (0.4 or 0.9.8) to version 1
--

ALTER TABLE USERS MODIFY LASTLOGIN TIMESTAMP DEFAULT NULL;

DROP INDEX `USERS__LOGIN` ON USERS;
CREATE INDEX `USERS__LOGIN` ON USERS (LOGIN(32));

DROP INDEX `USERS__NAME` ON USERS;
CREATE INDEX `USERS__NAME` ON USERS (NAME(10));

DROP INDEX `USERS__SECONDNAME` ON USERS;
CREATE INDEX `USERS__SECONDNAME` ON USERS (SECONDNAME(10));

DROP INDEX `USERS__SURNAME` ON USERS;
CREATE INDEX `USERS__SURNAME` ON USERS (SURNAME(10));

CREATE TABLE `SCHEMA_CHANGES`(
   `ID` int NOT NULL AUTO_INCREMENT,
   `VERSION_NUMBER` int NOT NULL,
   `SCRIPT_NAME` varchar(255) NOT NULL,
   `TIMESTAMP_UTC_APPLIED` varchar(19) NOT NULL,
   PRIMARY KEY (ID)
);

INSERT INTO `SCHEMA_CHANGES` (`VERSION_NUMBER`, `SCRIPT_NAME`, `TIMESTAMP_UTC_APPLIED`)
VALUES ('1', 'updateusers1.sql', UTC_TIMESTAMP());

DROP TABLE `INFORMATIONS`;
