-- Understanding the xID
-- M (MID): link to MASTER table
-- L (LID): link to LABELS table
-- S (SID): link to SOURCES table
-- D (DID): link to DRUGS table
-- M (MID): link to MOLS table
-- R (RID): link to ROUTES table
-- IA (IAID): link to INTERACTIONS table
-- IAK (IAKID): link to INTERACTION_KNOWLEDGE table
-- BIB_ID: link to BIBLIOGRAPHY table

-- In one to many tables
-- MASTER_xID: is used to link one to many: 1 MASTER_xID is many xID
-- AID_MASTER_LID: is used to link one authorization text to many translations in LABELS_LINK


-- Generic ATC table (more than 5000 ATC codes are known)
-- Codes ID > 100 000 are interacting molecule names without ATC
-- Codes ID > 200 000 are interactions classes denomination


-- Some queries

-- Get all drugs information (without composition) // SID can be retrived from the SOURCES table
-- SELECT DRUGS.* FROM MASTER
-- JOIN DRUGS ON DRUGS.DID=MASTER.DID
-- WHERE SID=1;

-- Get all drugs source labels
-- SELECT LABELS.LANG, LABELS.LABEL
-- FROM LABELS
-- JOIN SOURCES ON SOURCES.MASTER_LID=LABELS_LINK.MASTER_LID
-- JOIN LABELS_LINK ON LABELS_LINK.LID=LABELS.LID
-- WHERE SOURCES.DATABASE_UID="AFSSAPS_FR";

-- Get all route labels
-- SELECT LABELS.LANG, LABELS.LABEL
-- FROM LABELS
-- JOIN ROUTES ON ROUTES.MASTER_LID=LABELS_LINK.MASTER_LID
-- JOIN LABELS_LINK ON LABELS_LINK.LID=LABELS.LID
-- WHERE ROUTES.RID=3;

-- Get drug routes labels
-- SELECT LABELS.LANG, LABELS.LABEL
-- FROM DRUG_ROUTES
-- JOIN ROUTES ON ROUTES.RID=DRUG_ROUTES.RID
-- JOIN LABELS_LINK ON LABELS_LINK.MASTER_LID=ROUTES.MASTER_LID
-- JOIN LABELS ON LABELS_LINK.LID=LABELS.LID
-- WHERE DRUG_ROUTES.DID=3;

-- Get the RID from a route label
-- SELECT ROUTES.RID
-- FROM LABELS
-- JOIN LABELS_LINK ON LABELS_LINK.LID=LABELS.LID
-- JOIN ROUTES ON ROUTES.MASTER_LID=LABELS_LINK.MASTER_LID
-- WHERE LABELS.LABEL="intralymphatisch";

-- Get ATC ID, CODE, LABEL for one specific language
-- SELECT ATC.ATC_ID, ATC.CODE, LABELS.LABEL
-- FROM ATC
-- JOIN ATC_LABELS ON ATC_LABELS.ATC_ID=ATC.ATC_ID
-- JOIN LABELS_LINK ON LABELS_LINK.MASTER_LID=ATC_LABELS.MASTER_LID
-- JOIN LABELS ON LABELS_LINK.LID=LABELS.LID
-- WHERE LABELS.LANG="fr" AND ATC.ATC_ID=100;
-- Search a specific label
SELECT ATC.ATC_ID, ATC.CODE, LABELS.LABEL
FROM ATC
JOIN ATC_LABELS ON ATC_LABELS.ATC_ID=ATC.ATC_ID
JOIN LABELS_LINK ON LABELS_LINK.MASTER_LID=ATC_LABELS.MASTER_LID
JOIN LABELS ON LABELS_LINK.LID=LABELS.LID
WHERE LABELS.LANG="fr" AND LABELS.LABEL like 'ISO%';

-- Get risk infos about interactions
-- SELECT INTERACTIONS.IAID, INTERACTIONS.ATC_ID1, INTERACTIONS.ATC_ID2, LABELS.LANG, LABELS.LABEL
-- FROM INTERACTIONS
-- JOIN IA_IAK ON IA_IAK.IAID=INTERACTIONS.IAID
-- JOIN IAKNOWLEDGE ON IAKNOWLEDGE.IAKID=IA_IAK.IAKID
-- JOIN LABELS_LINK ON LABELS_LINK.MASTER_LID=IAKNOWLEDGE.RISK_MASTER_LID
-- JOIN LABELS ON LABELS_LINK.LID=LABELS.LID
-- WHERE INTERACTIONS.IAID=1;
-- Get management infos about interactions
-- SELECT INTERACTIONS.IAID, INTERACTIONS.ATC_ID1, INTERACTIONS.ATC_ID2, LABELS.LANG, LABELS.LABEL
-- FROM INTERACTIONS
-- JOIN IA_IAK ON IA_IAK.IAID=INTERACTIONS.IAID
-- JOIN IAKNOWLEDGE ON IAKNOWLEDGE.IAKID=IA_IAK.IAKID
-- JOIN LABELS_LINK ON LABELS_LINK.MASTER_LID=IAKNOWLEDGE.MAN_MASTER_LID
-- JOIN LABELS ON LABELS_LINK.LID=LABELS.LID
-- WHERE INTERACTIONS.IAID=1;

-- Find drugs according to their molecular component names
SELECT DRUGS.NAME, LK_MOL_ATC.ATC_ID, LABELS.LABEL
FROM DRUGS
JOIN COMPOSITION ON DRUGS.DID=COMPOSITION.DID
JOIN LK_MOL_ATC ON LK_MOL_ATC.MID=COMPOSITION.MID
JOIN ATC_LABELS ON ATC_LABELS.ATC_ID=LK_MOL_ATC.ATC_ID
JOIN LABELS_LINK ON LABELS_LINK.MASTER_LID=ATC_LABELS.MASTER_LID
JOIN LABELS ON LABELS_LINK.LID=LABELS.LID
WHERE LABELS.LABEL LIKE 'ISO%';

-- Find drugs according to their INN names
SELECT DRUGS.NAME, MOLS.NAME
FROM DRUGS
JOIN COMPOSITION ON DRUGS.DID=COMPOSITION.DID
JOIN MOLS ON COMPOSITION.MID=MOLS.MID
WHERE MOLS.NAME LIKE 'ISOSO%';


-- Get all molecule names related to a drug
SELECT MOLS.NAME
FROM DRUGS
JOIN COMPOSITION ON DRUGS.DID=COMPOSITION.DID
JOIN MOLS ON COMPOSITION.MID=MOLS.MID
WHERE DRUGS.DID=1;

-- Get all molecular names and related ATC_IDs for a specified drug
SELECT MOLS.NAME, LK_MOL_ATC.ATC_ID
FROM DRUGS
JOIN COMPOSITION ON DRUGS.DID=COMPOSITION.DID
JOIN MOLS ON COMPOSITION.MID=MOLS.MID
JOIN LK_MOL_ATC ON MOLS.MID=LK_MOL_ATC.MID
WHERE DRUGS.DID=1;

-- Get all molecular names and related ATC_IDs + name for a specified drug
SELECT MOLS.NAME, LK_MOL_ATC.ATC_ID, LABELS.LABEL
FROM DRUGS
JOIN COMPOSITION ON DRUGS.DID=COMPOSITION.DID
JOIN MOLS ON COMPOSITION.MID=MOLS.MID
JOIN LK_MOL_ATC ON MOLS.MID=LK_MOL_ATC.MID
JOIN ATC_LABELS ON ATC_LABELS.ATC_ID=LK_MOL_ATC.ATC_ID
JOIN LABELS_LINK ON LABELS_LINK.MASTER_LID=ATC_LABELS.MASTER_LID
JOIN LABELS ON LABELS_LINK.LID=LABELS.LID
WHERE DRUGS.DID=2 AND LABELS.LANG="en";


-- Get all interacting classes IDs related to one drug
SELECT IAM_TREE.ID_CLASS
FROM IAM_TREE
WHERE (IAM_TREE.ID_ATC IN (
  SELECT LK_MOL_ATC.ATC_ID
  FROM DRUGS
  JOIN COMPOSITION ON DRUGS.DID=COMPOSITION.DID
  JOIN MOLS ON COMPOSITION.MID=MOLS.MID
  JOIN LK_MOL_ATC ON MOLS.MID=LK_MOL_ATC.MID
  WHERE DRUGS.DID=1)
);

-- Get all interacting classes ID + names related to one drug
SELECT IAM_TREE.ID_CLASS, LABELS.LABEL
FROM IAM_TREE
JOIN ATC_LABELS ON ATC_LABELS.ATC_ID=IAM_TREE.ID_CLASS
JOIN LABELS_LINK ON LABELS_LINK.MASTER_LID=ATC_LABELS.MASTER_LID
JOIN LABELS ON LABELS_LINK.LID=LABELS.LID
WHERE (IAM_TREE.ID_ATC IN (
  SELECT LK_MOL_ATC.ATC_ID
  FROM DRUGS
  JOIN COMPOSITION ON DRUGS.DID=COMPOSITION.DID
  JOIN MOLS ON COMPOSITION.MID=MOLS.MID
  JOIN LK_MOL_ATC ON MOLS.MID=LK_MOL_ATC.MID
  WHERE DRUGS.DID=1)
) AND (LABELS.LANG="en");


-- DELETE trigger on drugs
CREATE TRIGGER cleanDrug BEFORE DELETE ON DRUGS
BEGIN
  -- Delete composition
  DELETE FROM COMPOSITION WHERE COMPOSITION.DID=old.DID;
  -- Delete Routes and Forms
  DELETE FROM DRUG_ROUTES WHERE DRUG_ROUTES.DID=old.DID;
  DELETE FROM DRUG_FORMS WHERE DRUG_FORMS.DID=old.DID;
END

-- DELETE trigger on composition
CREATE TRIGGER cleanComposition BEFORE DELETE ON COMPOSITION
BEGIN
  DELETE FROM MOLS WHERE MOLS.MID=old.MID;
END

-- DELETE trigger on forms labels
CREATE TRIGGER cleanFormLabels BEFORE DELETE ON DRUG_FORMS
BEGIN
  DELETE FROM LABELS_LINKS WHERE LABEL_LINKS.=old.;
END
