include( ../coreplugin/coreplugin.pri )
include( ../printerplugin/printerplugin.pri )
include( ../templatesplugin/templatesplugin.pri )
include( $${SOURCES_LIBS_PATH}/utils.pri)
include( $${SOURCES_LIBS_PATH}/translationutils.pri)
include( $${SOURCES_LIBS_PATH}/medicalutils.pri)
include( $${SOURCES_LIBS_PATH}/datapackutils.pri)
