CREATE TABLE IF NOT EXISTS `SUBSTANCES` (
  `ID` INTEGER PRIMARY KEY,
  `NAME` varchar(250) NOT NULL,
  `FILE` varchar(250) NOT NULL,
  `PARSED` date
);

CREATE TABLE IF NOT EXISTS `INFOS` (
  `ID` INTEGER PRIMARY KEY,
  `NAME` varchar(250),
  `COMPLEMENT` varchar(250) NOT NULL,
  `COMMENT` varchar(2000) NOT NULL,
  `PARSED` DATE,
  `TYPE` varchar(1)
);

CREATE TABLE IF NOT EXISTS `LINKS` (
  `SUBST_ID` INTEGER,
  `INFOS_ID` INTEGER
);

