CREATE TABLE IF NOT EXISTS `TMP_COMPOSITION` (
  `UID` int(10) NOT NULL,
  `MOLECULE_FORM` varchar(100),
  `MOLECULE_CODE` int(11) NOT NULL,
  `MOLECULE_NAME` varchar(200),
  `DOSAGE` varchar(100)  DEFAULT "",
  `DOSAGE_REF` varchar(50) DEFAULT "",
  `NATURE` varchar(2) NOT NULL DEFAULT "SA",
  `LK_NATURE` int(11) NOT NULL DEFAULT 1
);
