include( ../coreplugin/coreplugin.pri )
include( ../fmfcoreplugin/fmfcoreplugin.pri )
include( ../printerplugin/printerplugin.pri )
include( ../usermanagerplugin/usermanagerplugin.pri )
include( ../formmanagerplugin/formmanagerplugin.pri )
include( ../patientbaseplugin/patientbaseplugin.pri )
include( $${SOURCES_LIBS_PATH}/translationutils.pri )
include( $${SOURCES_LIBS_PATH}/utils.pri )
