######################################################################
# Automatically generated by qmake (2.00a) Sun Jun 26 21:12:22 2005
######################################################################

TEMPLATE = app
CONFIG += qt warn_on debug console
QT -= gui
DEPENDPATH += .
INCLUDEPATH += . ../..

# Input
SOURCES += main.cpp

unix {
  OBJECTS_DIR=.obj
  LIBS = -L../../quazip -lquazip
}

win32 {
    LIBS = -L../../quazip/debug -lquazip
}
win32-x-g++ {
    LIBS = -L../../quazip/debug -lquazip
}

