######################################################################
# Automatically generated by qmake (2.01a) ven. sept. 21 13:40:58 2012
######################################################################

TEMPLATE = app
TARGET = rapidtofree
DESTDIR = bin
MOC_DIR = moc
OBJECTS_DIR = o
UI_DIR = ui
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += /home/pmddeb/freemedforms_pmd_git/freemedforms/bin/freeaccount/plugins
LIBS+=-lAccountBase_debug

# Input
HEADERS += rapidtofreeio.h rapidtofreeviewer.h connect.h
SOURCES += main.cpp rapidtofreeio.cpp rapidtofreeviewer.cpp connect.cpp
FORMS += rapidtofree.ui connexiondialog.ui

QT += sql
