######################################################################
# Automatically generated by qmake (2.01a) ven. sept. 21 13:40:58 2012
######################################################################

TEMPLATE = app
TARGET = rapidtofree
DESTDIR = bin
MOC_DIR = moc
OBJECTS_DIR = o
UI_DIR = ui
DEPENDPATH += .
INCLUDEPATH += .

include( ../plugins/accountbaseplugin/accountbaseplugin.pri )

# Input
HEADERS += rapidtofreeio.h rapidtofreeviewer.h
SOURCES += main.cpp rapidtofreeio.cpp rapidtofreeviewer.cpp
FORMS += rapidtofree.ui
QT += sql
