include( ../coreplugin/coreplugin.pri )
include( ../printerplugin/printerplugin.pri )
include( ../texteditorplugin/texteditorplugin.pri )
include( ../listviewplugin/listviewplugin.pri )
include( ../identityplugin/identityplugin.pri )
include( ../zipcodesplugin/zipcodesplugin.pri )
include( $${SOURCES_LIBS_PATH}/utils.pri)
include( $${SOURCES_LIBS_PATH}/translationutils.pri)
