include( ../coreplugin/coreplugin.pri )
include( ../fdcoreplugin/fdcoreplugin.pri )
include( ../drugsplugin/drugsplugin.pri )
include( ../templatesplugin/templatesplugin.pri )
include( ../printerplugin/printerplugin.pri )
include( $${SOURCES_LIBS_PATH}/medintuxutils.pri )
