include(../coreplugin/coreplugin.pri)
include(../ddiplugin/ddiplugin.pri)
include( $${SOURCES_PLUGINS_PATH}/texteditorplugin/texteditorplugin.pri)
include( $${SOURCES_CONTRIBS_PATH}/quazip/quazip.pri )
include( $${SOURCES_LIBS_PATH}/datapackutils.pri )
