include( ../coreplugin/coreplugin.pri )
include( ../printerplugin/printerplugin.pri )
include( ../texteditorplugin/texteditorplugin.pri )
include( ../accountbaseplugin/accountbaseplugin.pri )
include( ../zipcodesplugin/zipcodesplugin.pri )
include( ../listviewplugin/listviewplugin.pri )
