include(../coreplugin/coreplugin.pri)
include(../usermanagerplugin/usermanagerplugin.pri)
include(../patientbaseplugin/patientbaseplugin.pri)
include(../listviewplugin/listviewplugin.pri)
include($${SOURCES_LIBS_PATH}/calendar.pri)
