SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `CATEGORIES` (
  `CID` int(10) UNSIGNED NOT NULL,
  `UUID` varchar(200) DEFAULT NULL,
  `PARENT_ID` int(11) DEFAULT NULL,
  `LID` int(11) DEFAULT NULL,
  `MIME` varchar(200) DEFAULT NULL,
  `PID` int(11) DEFAULT NULL,
  `SORT_ID` int(11) DEFAULT NULL,
  `PASSWORD` varchar(200) DEFAULT NULL,
  `VALID` int(1) DEFAULT '1',
  `THEMED_ICON` varchar(200) DEFAULT NULL,
  `EXTRA` varchar(2000) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `LABEL` (
  `ID` int(10) UNSIGNED NOT NULL,
  `LID` int(11) DEFAULT NULL,
  `LANG` varchar(2) DEFAULT NULL,
  `VALUE` varchar(200) DEFAULT NULL,
  `VALID` int(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `PROTECTION` (
  `ID` int(10) UNSIGNED NOT NULL,
  `PID` int(11) DEFAULT NULL,
  `USER_RESTRICTED` varchar(32) DEFAULT NULL,
  `GROUP_RESTRICTED` varchar(32) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `SCHEMA_CHANGES` (
  `ID` int(11) NOT NULL,
  `VERSION_NUMBER` int(11) NOT NULL,
  `SCRIPT_NAME` varchar(255) NOT NULL,
  `TIMESTAMP_UTC_APPLIED` varchar(19) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


ALTER TABLE `CATEGORIES`
  ADD PRIMARY KEY (`CID`),
  ADD KEY `CATEGORIES__CID` (`CID`),
  ADD KEY `CATEGORIES__PARENT_ID` (`PARENT_ID`),
  ADD KEY `CATEGORIES__LID` (`LID`),
  ADD KEY `CATEGORIES__PID` (`PID`),
  ADD KEY `CATEGORIES__SORT_ID` (`SORT_ID`),
  ADD KEY `CATEGORIES__UUID` (`UUID`(190)),
  ADD KEY `CATEGORIES__MIME` (`MIME`(190));

ALTER TABLE `LABEL`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `LABEL__ID` (`ID`),
  ADD KEY `LABEL__LID` (`LID`),
  ADD KEY `LABEL__LANG` (`LANG`);

ALTER TABLE `PROTECTION`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `PROTECTION__ID` (`ID`),
  ADD KEY `PROTECTION__PID` (`PID`);

ALTER TABLE `SCHEMA_CHANGES`
  ADD PRIMARY KEY (`ID`);


ALTER TABLE `CATEGORIES`
  MODIFY `CID` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=25;
ALTER TABLE `LABEL`
  MODIFY `ID` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=169;
ALTER TABLE `PROTECTION`
  MODIFY `ID` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `SCHEMA_CHANGES`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
