######################################################################
# Automatically generated by qmake (2.01a) mer. avr. 13 09:44:38 2011
######################################################################

TEMPLATE = app
TARGET = parse_CCAM
DESTDIR = ./bin
DEPENDPATH += .
INCLUDEPATH += .
MOC_DIR = ./moc
OBJECTS_DIR = ./o
UI_DIR = ./ui

# Input
HEADERS += parseCCAM.h findFile.h
SOURCES += main.cpp parseCCAM.cpp findFile.cpp
FORMS += parse.ui

QT += sql
