######################################################################
# Automatically generated by qmake (2.01a) jeu. févr. 10 21:18:26 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += movementsviewer.h
FORMS += movementsviewer.ui
SOURCES += main.cpp movementsviewer.cpp
