######################################################################
# Automatically generated by qmake (2.01a) jeu. févr. 10 21:18:26 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
MOC_DIR += moc
OBJECTS_DIR += o
UI_HEADERS_DIR += ui_h

# Input
HEADERS += movementsviewer.h
FORMS += movementsviewer.ui
SOURCES += main.cpp movementsviewer.cpp
