ALTER TABLE PATIENT_IDENTITY ADD COLUMN MOBILE_PHONE varchar(32);

ALTER TABLE PATIENT_IDENTITY ADD COLUMN WORK_PHONE varchar(32);

CREATE TABLE SCHEMA_CHANGES(
   ID integer PRIMARY KEY NOT NULL,
   VERSION_NUMBER integer NOT NULL,
   SCRIPT_NAME varchar(255) NOT NULL,
   TIMESTAMP_UTC_APPLIED varchar(19) NOT NULL);

DROP TABLE VERSION;

INSERT INTO SCHEMA_CHANGES(VERSION_NUMBER, SCRIPT_NAME, TIMESTAMP_UTC_APPLIED) VALUES(1, 'updatesqlitepatients1.sql', datetime());

