DROP INDEX `PATIENT_IDENTITY__NAME` ON PATIENT_IDENTITY;
CREATE INDEX `PATIENT_IDENTITY__NAME` ON PATIENT_IDENTITY (NAME(10));

DROP INDEX `PATIENT_IDENTITY__SURNAME` ON PATIENT_IDENTITY;
CREATE INDEX `PATIENT_IDENTITY__SURNAME` ON PATIENT_IDENTITY (SURNAME(10));

DROP INDEX `PATIENT_IDENTITY__SECONDNAME` ON PATIENT_IDENTITY;
CREATE INDEX `PATIENT_IDENTITY__SECONDNAME` ON PATIENT_IDENTITY (SECONDNAME(10));

ALTER TABLE `PATIENT_IDENTITY` ADD COLUMN `USER_UUID` BINARY(16);
CREATE INDEX `PATIENT_IDENTITY__USER_UUID` ON PATIENT_IDENTITY (USER_UUID);

INSERT INTO `SCHEMA_CHANGES` (`VERSION_NUMBER`, `SCRIPT_NAME`, `TIMESTAMP_UTC_APPLIED`)
VALUES ('2', 'updatepatients2.sql', UTC_TIMESTAMP());
