include( ../coreplugin/coreplugin.pri )
include( ../usermanagerplugin/usermanagerplugin.pri )
include( $${SOURCES_LIBS_PATH}/extensionsystem.pri )
include( $${SOURCES_LIBS_PATH}/translationutils.pri )
include( $${SOURCES_LIBS_PATH}/utils.pri )
include( $${SOURCES_LIBS_PATH}/medicalutils.pri )
