include( ../coreplugin/coreplugin.pri )
include( ../identityplugin/identityplugin.pri )
include( ../formmanagerplugin/formmanagerplugin.pri )
include( ../usermanagerplugin/usermanagerplugin.pri)
include( ../listviewplugin/listviewplugin.pri )
include( ../zipcodesplugin/zipcodesplugin.pri )

include( $${SOURCES_LIBS_PATH}/extensionsystem.pri )
include( $${SOURCES_LIBS_PATH}/translationutils.pri )
include( $${SOURCES_LIBS_PATH}/utils.pri )
include( $${SOURCES_LIBS_PATH}/medicalutils.pri )
