.TH FreeMedForms 1 "29 April 2011"
.SH NAME
FreeMedForms - Electronic Medical Record manager
.SH SYNOPSIS
.B freemedforms
.SH DESCRIPTION
.B FreeMedForms
is a free and open source Electronic Medical Record
manager.
.B FreeMedForms
is developed by a international community of
medical doctors and computer workers and is
mainly intended for health professionals.
.P
Currently, the suite is under development. It is
available only for testing purposes.
The main objective of
.B FreeMedForms
is to manage the
electronic medical records based on your
medical practice or the practice of clinical
research groups.

.SH "OPTIONS"
.LP
.TP
\fB\-v / --version\fR
Displays the current version of FreeDiams.
.TP
.P
More parameters are documented at
.P
http://www.freemedforms.com/en/manuals/freemedforms

.SH AUTHOR
.B FreeMedForms
is copyright 2008-2011 by Eric Maeker, MD
.SH "SEE ALSO"
.B FreeDiams
Pharmaceutical drugs prescriptor, result of the
prescriber plugin built into a standalone
application.
.br
.B http://www.freemedforms.com/
