DROP INDEX `EPISODES__FORM_PAGE_UID` ON EPISODES;
CREATE INDEX `EPISODES__FORM_PAGE_UID` ON EPISODES (FORM_PAGE_UID(190));

DROP INDEX `FORM_FILES__SUBUID` ON FORM_FILES;
CREATE INDEX `FORM_FILES__SUBUID` ON FORM_FILES (SUBUID(190));

DROP INDEX `FORM_FILES__IP` ON FORM_FILES;
CREATE INDEX `FORM_FILES__IP` ON FORM_FILES (IP(190));

DROP TABLE `VERSION`;

CREATE TABLE `SCHEMA_CHANGES`(
   `ID` int NOT NULL AUTO_INCREMENT,
   `VERSION_NUMBER` int NOT NULL,
   `SCRIPT_NAME` varchar(255) NOT NULL,
   `TIMESTAMP_UTC_APPLIED` varchar(19) NOT NULL,
   PRIMARY KEY (ID)
);

INSERT INTO `SCHEMA_CHANGES` (`VERSION_NUMBER`, `SCRIPT_NAME`, `TIMESTAMP_UTC_APPLIED`)
VALUES ('3', 'updateepisodes3.sql', UTC_TIMESTAMP());
